### ISSUE TITLE
Amelioration page team

### ISSUE THREAD

**Issue by LucasBokser** [LucasBokser/Site-entreprise#2]
- Refonte Graphique
- Amélioration de contenu
- Changement de couleur

**Comment by julienma** [comment]
Ça c'est top : une issue qui décrit la fonctionnalité, un détail de ce qui est attendu concrètement, et on a quasi 1 commit par changement (cf. https://www.pauline-vos.nl/atomic-commits/), tous bien taggués avec le numéro de l'issue correspondante. Clair, bravo.
