### ISSUE TITLE
Compétence "Résoudre des conflits lors d'un merge"

### ISSUE THREAD

**Issue by julienma** [LucasBokser/Site-entreprise#5]
@ChristopheHALLER @LucasBokser @RobinPoulet @Elise-FR je vous fais un message commun à propos de la résolution de conflit, comme vous êtes tous les 4 dans la même situation.

Les "preuves" que vous m'avez données sur Campus Skills ne montrent pas une résolution de conflit.

Vous avez effectivement eu un problème suite à un `git pull` à cause des `desktop.ini`. Mais il n'y a pas eu de résolution de merge, tout simplement car il n'y a pas eu de merge.
Vous êtes sortis de cette situation en faisant un `git restore .`. Cela revient à ignorer tous les changements amenés par le pull-merge, et non pas à les résoudre.

Le bon point : le problème a été réglé.
Le mauvais point : il me manque toujours une vraie résolution de conflit :)

Ce que je voudrais comme preuve : un screenshot de votre terminal avec le `git  pull` qui montre qu'il y a un conflit, et le screenshot qui montre que vous avez résolu le conflit (suppression des marqueurs de conflits `<<<< ==== >>>> etc` dans le code) grâce au commit qui fait passer le statut de votre repo de `master|MERGING` à `master` tout court, cf. cet exemple random trouvé sur internet : 

![Bitmap](https://user-images.githubusercontent.com/201897/118108799-b70c1280-b3e0-11eb-8aeb-379f18ce03ec.png)

Pour créer un conflit : soit vous éditez à plusieurs la même ligne (genre un `<title>` du même fichier), soit vous éditez d'un côté en local et de l'autre côté via Github. C'est expliqué p8 du PDF, dans l'exercice n°6 "Gérer les conflits (en individuel)", et pour que ce soit clair je vous ai fait une vidéo d'exemple :

https://user-images.githubusercontent.com/201897/118109539-a14b1d00-b3e1-11eb-95a5-f4cf144ee82b.mp4

**Comment by LucasBokser** [comment]
On a fait un merge avec l'ilot, tu peux aller voir dans G:\Drive
partagés\Tech Dev WebApp Étudiants 2022\Modules\06. Git\Rendus\Elise
Franzini\Conflit Merge

Cordialement,

Lucas Bokser

**Comment by Elise-FR** [comment]
Salut Julien,

On a fait un conflit pour pouvoir résoudre un Merge. Je t'ai tout mis dans
Elise Franzini , dans le dossier Conflit Merge.
On est l'ilot 3 !

Dis nous si c'est tout bon !! ;)

Encore merci pour l'aide !

A bientôt !

Elise

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by julienma** [comment]
Nickel, merci :)

**Comment by LucasBokser** [comment]
Bon week-end !!!
